import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import React from 'react';

import BG_TOP from '@/public/bg_top.webp';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='body-container'>
					<div className='main-container'>{children}</div>
					<div className='flex-none h-[600px] w-[1200px] max-w-[1200px] pointer-events-none z-0 absolute top-0'>
						<Image
							alt='Gradient Background'
							src={BG_TOP}
							className='pointer-events-none select-none w-full h-full object-center object-cover'
						/>
					</div>
				</div>
			</body>
		</html>
	);
}
