import type { Metadata } from 'next';
import dynamic from 'next/dynamic';

import Featured from '@/components/Home/Featured';
import Me from '@/components/Home/Me';

const Contact = dynamic(() => import('@/components/Home/Contact'));

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function Home() {
	return (
		<>
			<Me />
			<Featured type='work' />
			<Featured type='project' />
			<Contact />
		</>
	);
}
